### ISSUE TITLE
Visual Bug - Incorrect/duplicate tiles showing?

### ISSUE THREAD

**Issue by itspamlam** [digirati-co-uk/iiif-canvas-panel#229]
For certain canvases, there is a bug where it looks like incorrect and/or duplicate tiles are showing (at different zoom levels).

This can be seen when trying to view -
manifest: https://media.getty.edu/iiif/manifest/1e0ed47e-5a5b-4ff0-aea0-45abee793a1c
canvas-id: https://media.getty.edu/iiif/manifest/canvas/d79a007d-c4b9-4e63-a220-e3b4998157dd.json

You can just plug it into the demo at: https://iiif-canvas-panel.netlify.app/all-sandboxes#intro-script

Instead of displaying (as seen on Mirador viewer):
 
<img width="1246" alt="Screenshot 2023-12-12 at 2 53 51 PM" src="https://github.com/digirati-co-uk/iiif-canvas-panel/assets/25655259/955d7215-8d6b-4104-8ade-9d8d35b8060c">

The display on Canvas Panel is:
<img width="1338" alt="Screenshot 2023-12-12 at 2 52 50 PM" src="https://github.com/digirati-co-uk/iiif-canvas-panel/assets/25655259/bb969eb8-965d-4474-80d2-5a7c8976636e">

**Comment by stephenwf** [comment]
Hi @itspamlam, I think Canvas Panel will sometimes use the thumbnail as a lower quality source to improve loading speeds (although we should probably make that optional). In the manifest the `height` and `width` provided do not match the aspect ratio of the canvas - I _think_ this is what is causing the problem.

**Comment by itspamlam** [comment]
@stephenwf Thanks for getting back to me!

What or where could I have found what aspect ratio the canvas was expecting? Are there any settings/attributes I could currently use to work around this issue?

**Comment by stephenwf** [comment]
```diff
{
  "@id": "https://media.getty.edu/iiif/manifest/canvas/bb72d5f1-e230-4797-a7dc-262bf948b256.json",
  "@type": "sc:Canvas", 
  "height": 6512, 
  "images": [...], 
  "label": "Full front, post-conservation", 
  "license": "http://creativecommons.org/publicdomain/zero/1.0/", 
  "metadata": [...], 
  "thumbnail": {
    "@id": "https://media.getty.edu/iiif/image/bb72d5f1-e230-4797-a7dc-262bf948b256/full/!600,600/0/default.jpg", 
    "@type": "dctypes:Image", 
    "format": "image/jpeg", 
+    "height": 600, 
    "label": "Full front, post-conservation", 
    "service": {
      "@context": "http://iiif.io/api/image/2/context.json", 
      "@id": "https://media.getty.edu/iiif/image/bb72d5f1-e230-4797-a7dc-262bf948b256", 
      "profile": "http://iiif.io/api/image/2/level2.json"
    }, 
+    "width": 600
  }, 
  "width": 4488
}
```
These are the lines that may be causing the issue. The thumbnail is `600 x 600` but the canvas and image are `4488 x 6512`. So if the thumbnail matched the canvas aspect ratio it would be `414 x 600` 

This also matches the served image:
https://media.getty.edu/iiif/image/bb72d5f1-e230-4797-a7dc-262bf948b256/full/!600,600/0/default.jpg

So if the JSON was slightly different, with accurate height/width then it would render correctly. 

I've published `@digirati/canvas-panel-web-components@1.0.58` which includes a new attribute `disable-thumbnail="true"` which can be added to the `<canvas-panel />` component to prevent the thumbnail from being used.

**Comment by itspamlam** [comment]
Hi @stephenwf 

I updated my version of Canvas Panel & attempted to use the new attribute but was still getting/seeing this same issue. I also served a local version of my manifest with the correct thumbnail size(s) & that did not solve the issue either.

However, I did notice something that may or may not be related to this issue. The canvases that are having this issue happen to also have less scaleFactors available in the info.json. For example:
info.json: https://media.getty.edu/iiif/image/d79a007d-c4b9-4e63-a220-e3b4998157dd/info.json
canvas-id: https://media.getty.edu/iiif/manifest/canvas/d79a007d-c4b9-4e63-a220-e3b4998157dd.json
manifest: https://media.getty.edu/iiif/manifest/1e0ed47e-5a5b-4ff0-aea0-45abee793a1c

I am also seeing bad requests in my console for image sizes that are not available. Does Canvas Panel have certain expectations for the amount of scaleFactors/sizes available? This seems to be happening for smaller images with less scaleFactors available.

**Comment by stephenwf** [comment]
Hi @itspamlam, hmm, that's strange. Yes it's possible it's having difficulties with the smaller size. Maybe an issue with rounding. I'll look into it further

**Comment by danieltbrennan** [comment]
Hi @stephenwf I was able to look a little closer at this and I think we've better identified the issue. Owing to the way our manifests are generated in a subset of them we're providing dimensions for the canvas and embedded image service that don't match the dimensions provided by the actual image service. 

In the example above, the canvas specifies a h x w of 1068 x 700 for the resource while the response from the image service specifies 768 x 503. I think the differing dimensions and probably even more so the differing aspect ratios is the source of the visual issues we're seeing on these types of images. 

In digging I _think_ I found where this could be caught so put together a PR to illustrate:  https://github.com/digirati-co-uk/iiif-canvas-panel/pull/235. When testing in storybook with our problematic image it renders cleanly but not sure if there might be other concerns.

**Comment by stephenwf** [comment]
Ah that's very possible. Atlas does try to rescale where it can, but it so far worked best with static images, picking the best size to render. It could be a bug with tiled images. I've seen something similar (but not exactly the same) with Wellcome manifests. They specify an image service that's bigger than the canvas - which I think is the opposite problem.

Thanks for looking into it. If we can get a test fixture, I can look deeper in the tile generation.

**Comment by danieltbrennan** [comment]
Wanted to update this as we've been able to somewhat address it with the previous PR but are still seeing some issues that appear to be related in other places. Sharing everything we can here @stephenwf in case it sparks any thoughts on where to look to potentially address this.

Test Manifest: https://gist.githubusercontent.com/danieltbrennan/20c7b504613a44ed9728ef05b33ba837/raw/3f8e7f71e60d94d1481071bdb45498e844d387c2/getty_canvaspanel_test-composite.json

When loading this manifest into Canvas Panel (in Storybook and within our applications) we're consistently seeing the same kind of morphed tiles mentioned above when panning and zooming canvases that have multiple images painted on a canvas (canvases 3 and 7 in the test fixture linked above)

![Screen Shot 2024-03-05 at 3 19 01 PM](https://github.com/digirati-co-uk/iiif-canvas-panel/assets/1169887/4edd4da6-88b0-4c12-aeb3-f99533bc3151)

Though visually similar to what we were observing on the images with mismatched image dimensions, in this case we can verify that the dimensions in the manifest are valid relative to the size/aspect ratio of the source image service.

An odd observation that may be worth noting is that in some way the order in which the canvases are loaded into the viewer seems to matter somewhat. If I reorder things so that one of the affected canvases is always the first displayed, it renders and zooms cleanly. 

This occurs in both `CanvasPanel` and `RangePanel` so would lead us to believe it's likely an issue in or closer to Atlas, but so far haven't had much luck identifying what the source might be, and getting these types of canvases to render properly along with the question of how to set an initial zoom level that never upscales (will open a separate issue on that) are probably the top issues we're trying to work through tied to an upcoming project. Thanks for any insight, it's much appreciated.

**Comment by stephenwf** [comment]
Thanks @danieltbrennan 

It does look like an issue closer to Atlas. I will try and get an example working in the Atlas storybook. I did try it in the latest version of React IIIF Vault (with previous sizes fix) and it does render correctly for me. Can you confirm that:

https://deploy-preview-170--react-iiif-vault-demo.netlify.app/#?manifest=https://gist.githubusercontent.com/danieltbrennan/20c7b504613a44ed9728ef05b33ba837/raw/3f8e7f71e60d94d1481071bdb45498e844d387c2/getty_canvaspanel_test-composite.json

Not sure what's different here, it might be the `@atlas-viewer/iiif-image-api` library, but hard to say. You mentioned the order, and this is something that has caused issues before.

I did previously add a test for image services in order:
https://github.com/atlas-viewer/iiif-image-api/blob/main/__tests__/image-service-loader.test.ts#L383-L495

This is a feature that I'm really considering removing - or putting behind a flag for everything. Essentially it tries to cut down on the number of `info.json` requests by guessing the sizes and tiles supported by the server. It makes X number of requests - compares its "guess" and if its correct X number of times, it stops making `info.json` requests. It works 99.9% of the time and saved a lot of requests..  but it's a horrible to debug when it doesn't work.

**Comment by danieltbrennan** [comment]
@stephenwf can confirm that things are rendering correctly in the latest version of React IIIF Vault linked above. We also tried loading one of our other problematic fixtures in that same environment and still see the issue: https://deploy-preview-170--react-iiif-vault-demo.netlify.app/#?manifest=https://media.getty.edu/iiif/manifest/1e0ed47e-5a5b-4ff0-aea0-45abee793a1c

The main difference in what the two manifests are providing is that the image service dimensions provided in the second manifest do not match those provided by the actual image service for canvases 4-6.

**Comment by stephenwf** [comment]
Ah yes, I can see that now with that Manifest. So there's definitely something else that needs fixed there.

**Comment by stephenwf** [comment]
We could probably construct a simple worst case to test with:

- Canvas: 1000x1000
- Image: 750x750
- Image service: 500x500

And then the opposite:

- Canvas: 500x500
- Image 750x750
- Image service: 1000x1000

And then a chaotic one for good measure:

- Canvas: 750x750
- Image: 1000x1000
- Image service: 500x500

Somewhere Atlas or Canvas Panel isn't taking into account the potential difference and scaling of these 3 items. I suspect it's using the Image as the source of truth. 


The [Manifest Editor](https://manifest-editor.digirati.services/) is useful for testing the limitations:
![image](https://github.com/digirati-co-uk/iiif-canvas-panel/assets/8266711/a5868f20-fe6a-4b32-a900-4c66cb53a2ec)

Here I took the image service, and then increased the canvas to 2000x2000. 

Even if I change the Image to also be 2000x2000, because the image service is smaller, it really doesn't like it. 


However, if I change the target of the annotation to be:
```
https://example.org/canvas-1#xywh=0,0,2000,2000
```

Then it works. So there is something really wrong with the target I think.

**Comment by danieltbrennan** [comment]
Thanks again for taking a look at this. Following along with what you're seeing, Interestingly the viewer in the manifest editor is one place where we do not see those types of visual artifacts on the composites. However on export there differences in the target as described in the manifest and the target as understood and painted in the canvas panel instance. 

Editor:
![Screen Shot 2024-03-07 at 2 38 45 PM](https://github.com/digirati-co-uk/iiif-canvas-panel/assets/1169887/003be6e3-8016-4859-9f1f-2641a403dede)

React-IIIF-Vault:
![Screen Shot 2024-03-07 at 2 40 30 PM](https://github.com/digirati-co-uk/iiif-canvas-panel/assets/1169887/36b97d48-065e-4cdf-8cd4-be05bbe02473)

Canvas Panel:
![Screen Shot 2024-03-07 at 2 40 04 PM](https://github.com/digirati-co-uk/iiif-canvas-panel/assets/1169887/81b4222f-9f53-4ec1-863a-65612f4f219d)

**Comment by stephenwf** [comment]
Definitely requires more investigating. That's quite a large difference between them all. Perhaps theres something in the Manifest Editor, a fix for positioning thats not been applied correctly to RIV and Canvas Panel

Another thing you can try is adding `<canvas-panel debug="true />` (or sequence panel) to see where Atlas is _trying_ to paint resources.

**Comment by stephenwf** [comment]
I think I found the issue(s).

The first:
- The image service width/height are not correctly used in RIV.
- The image service caching is causing issues, if the `service` block doesn't have a height/width

So I've deployed a new version of the IIIF Image API that doesn't cache by default. I've been meaning to do this for a while, so it's opt in now. 

If you confirm that this viewer is producing accurate representation, then I can publish the package and hopefully make the quick change to Canvas Panel too.


Same preview as before:

https://deploy-preview-170--react-iiif-vault-demo.netlify.app/#?manifest=https://media.getty.edu/iiif/manifest/1e0ed47e-5a5b-4ff0-aea0-45abee793a1c

https://deploy-preview-170--react-iiif-vault-demo.netlify.app/#?manifest=https://gist.githubusercontent.com/danieltbrennan/20c7b504613a44ed9728ef05b33ba837/raw/3f8e7f71e60d94d1481071bdb45498e844d387c2/getty_canvaspanel_test-composite.json

**Comment by danieltbrennan** [comment]
@stephenwf This is looking good to me, I'm not seeing any of the artifacting or distortions in the test cases. I've also tested a few other manifests that we have and they similarly render properly, so I think this is good to publish and implement in Canvas Panel.

**Comment by stephenwf** [comment]
That's great! I'll publish it tomorrow. Thanks again for all the investigation into this issue. We are starting to squash these harder bugs and the quality of the code is better for it!

**Comment by abrin** [comment]
@danieltbrennan @itspamlam do we feel like this image can be 'closed'?

**Comment by danieltbrennan** [comment]
Yes, this can be closed now
